server:
  port: 80
  servlet:
    context-path: /mq
apache:
  rocketmq:
    consumer:
      PushConsumer: C_LNCT_kkk
    producer:
      producerGroup: CGID_LOANCREDIT_ANTIFRAUD_JC5WK
    namesrvAddr: 10.50.180.161:9876;10.50.180.183:9876