server:
  port: 80
  servlet:
    context-path: /mq
apache:
  rocketmq:
    consumer:
      PushConsumer: PushConsumer
    producer:
      producerGroup: Producer
    namesrvAddr: 172.18.100.139:9876;172.18.100.169:9876