server:
  port: 8088
spring:
  redis:
    database: 0
    host: 192.168.69.52
    port: 6388
#    password: ""
#    ssl: false
#    timeout: 1000ms
  #    cluster:
  #      nodes:
  #    sentinel:
  #      master:
  #      nodes:
