server:
  port: 8088

spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    api-a:
      path: /eureka/**
      service-id: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enable: true
