server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti6ui?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://172.18.101.97:3306/activiti?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: activiti
#    password: activiti
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full

