server:
  port: 8989

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/flowableDemo
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

flowable:
  check-process-definitions: false
  idm:
    password-encoder: spring_delegating # 开安全验证

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path:
  endpoint:
    health:
      show-details: when_authorized
