server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
spring:
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CodeTest?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example

